<?php

define('FORM_EMBED_LOGIN_DISPLAY_ALWAYS', 0);
define('FORM_EMBED_LOGIN_DISPLAY_CLICK', 1);

function form_embed_login_form_node_type_form_alter(&$form, &$form_state) {
  $settings = $form['#node_type']->type ? variable_get('form_embed_login_' . $form['#node_type']->type, array()) : array();
  $form['form_embed_login'] = array(
    '#type' => 'fieldset',
    '#title' => t('Form embed login'),
    '#group' => 'additional_settings',
    'settings' => array(
      'status' => array(
        '#title' => t('Enabled'),
        '#type' => 'checkbox',
        '#parents' => array('form_embed_login', 'status'),
        '#default_value' => isset($settings['status']) ? $settings['status'] : 0
      ),
      'display' => array(
        '#title' => t('form embed login display'),
        '#type' => 'select',
        '#options' => array(
          FORM_EMBED_LOGIN_DISPLAY_ALWAYS => t('display always'),
          FORM_EMBED_LOGIN_DISPLAY_CLICK => t('display click')
        ),
        '#parents' => array('form_embed_login', 'display'),
        '#default_value' => isset($settings['display']) ? $settings['display'] : FORM_EMBED_LOGIN_DISPLAY_ALWAYS,
        '#states' => array(
          'visible' => array(
            ':input[name="form_embed_login[status]"]' => array('checked' => TRUE),
          ),
        ),
      ),
      'message' => array(
        '#title' => t('form embed login message'),
        '#type' => 'textarea',
        '#parents' => array('form_embed_login', 'message'),
        '#default_value' => isset($settings['message']) ? $settings['message'] : '',
        '#states' => array(
          'visible' => array(
            ':input[name="form_embed_login[status]"]' => array('checked' => TRUE),
          ),
        ),
      ),
      'close' => array(
        '#title' => t('form embed login close'),
        '#type' => 'select',
        '#options' => array(
          0 => 'Disable',
          1 => 'Enabled'
        ),
        '#parents' => array('form_embed_login', 'close'),
        '#default_value' => isset($settings['close']) ? $settings['close'] : 0,
        '#states' => array(
          'visible' => array(
            ':input[name="form_embed_login[status]"]' => array('checked' => TRUE),
          ),
        ),
      )
    )
  );
  array_unshift($form['#submit'], 'form_embed_login_form_node_type_form_submit');
}

function form_embed_login_form_node_type_form_submit($form, &$form_state) {
  variable_set('form_embed_login_' . $form_state['values']['type'], $form_state['values']['form_embed_login']);
  unset($form_state['values']['form_embed_login']);
}

function form_embed_login_form_alter(&$form, &$form_state, &$form_id) {
  if (strpos($form_id, '_node_form') !== FALSE) {
    $settings = variable_get('form_embed_login_' . $form['#node']->type, array());
    if (!empty($settings['status']) && form_embed_login_set_access() == NODE_ACCESS_ALLOW) {
      $login_form = drupal_get_form('user_login_block');
      $form['#suffix'] = '<div class="embed-login">'
          . (!empty($settings['message']) ? '<div class="embed-login-message">' . $settings['message'] . '</div>' : '')
          . (!empty($settings['close']) ? '<span class="embed-login-close">x</span>' : '')
          . drupal_render($login_form) . '</div>';
      if (!empty($settings['display']) && $settings['display'] == FORM_EMBED_LOGIN_DISPLAY_CLICK) {
        $form['#attached']['js'][] = drupal_get_path('module', 'form_embed_login') . '/form_embed_login.js';
      }
      $form['#validate'][] = 'form_embed_login_validate';
    }
  }
}

function form_embed_login_validate(&$form, &$form_state) {
  if (user_is_anonymous() && form_embed_login_set_access() == NODE_ACCESS_ALLOW) {
    form_set_error('', t('Please login first'));
  }
}

function form_embed_login_node_access($node, $op, $account) {
  if ($op == 'create' && user_is_anonymous()) {
    $settings = variable_get('form_embed_login_' . $node, array());
    if (!empty($settings['status'])) {
      return form_embed_login_set_access(NODE_ACCESS_ALLOW);
    }
  }
}

function form_embed_login_set_access($node_access = NULL) {
  $access = &drupal_static('form_embed_login_node_access', NODE_ACCESS_IGNORE);
  if (!empty($node_access)) {
    $access = $node_access;
  }
  return $access;
}
